fix(1007): adding shared keyring mode to type unit
dracutdevs/dracut pull request #1014
Opened 2021-01-18 16:20 UTC by johannbg

This pull request adds a shared keyring mode to dracut-pre-pivot.service as requested thus fixes #1007

2021-01-18 17:52 UTC, mikhailnov requested changes

2021-01-18 17:52 UTC, mikhailnov commented on modules.d/98dracut-systemd/dracut-pre-pivot.service
> +KeyringMode=shared
There is a trailing whitespace in the end of this string

2021-01-19 11:42 UTC, mikhailnov commented
Now there are two similar commits here, could you please make one and force push?

```
git reset --soft <ID of the first commit>
git add .
git commit --amend
git push origin +<branch-name>
```

2021-01-19 11:44 UTC, mikhailnov commented
Also, you can skip a line after the first line of the commit message and add text like this:

`Fixes: https://github.com/dracutdevs/dracut/issues/1007`

then github will automatically make a link from the PR to this issue and from the issue to the PR and will automatically close the ussie when the PR is merged. And there will be a link to the issue in the history of commits.

2021-01-19 12:28 UTC, johannbg commented
@mikhailnov thanks for the tips. :+1:

2021-01-19 12:30 UTC, mikhailnov commented
Now it looks much better, thanks!

2021-01-19 15:51 UTC, haraldh approved these changes

2021-01-26 09:19 UTC, johannbg commented
@danimo  ping...

2021-01-26 17:50 UTC, danimo approved these changes

2021-01-26 18:05 UTC, merged