feat(systemd-sysctl): add systemd-sysctl to spec file
dracutdevs/dracut pull request #1031
Opened 2021-01-26 17:34 UTC by johannbg

This pull request introduces systemd-sysctl module...

2021-02-08 23:01 UTC, danimo approved these changes

2021-02-09 15:32 UTC, haraldh requested changes

2021-02-09 15:32 UTC, haraldh commented on modules.d/01systemd-sysctl/module-setup.sh
> +            $systemdsystemconfdir/systemd-sysctl.service.d/*.conf
backslash missing

2021-02-09 15:32 UTC, haraldh commented on modules.d/01systemd-sysctl/module-setup.sh
> +    systemctl -q --root "$initdir" enable systemd-sysctl.service
$SYSTEMCTL

2021-02-09 16:36 UTC, johannbg commented on modules.d/01systemd-sysctl/module-setup.sh
> +            $systemdsystemconfdir/systemd-sysctl.service.d/*.conf
Fixed

2021-02-09 16:36 UTC, johannbg commented on modules.d/01systemd-sysctl/module-setup.sh
> +    systemctl -q --root "$initdir" enable systemd-sysctl.service
Fixed

2021-02-10 12:43 UTC, haraldh commented
Depends on https://github.com/dracutdevs/dracut/pull/1022 .. waiting with review until it is merged

2021-02-10 13:52 UTC, haraldh approved these changes

2021-02-10 14:00 UTC, merged