inst_multiple: globbing vs sysroot
dracutdevs/dracut pull request #1041
Opened 2021-01-30 13:42 UTC by zboszor

The file pattern passed to inst_multiple (if not quoted) is immediately substituted by the shell.
When dracutsysrootdir is set and the same package is not installed on the host then the files are obviously not found on the host system. dracut-install complains loudly in this case.

This can also create an issue if the package versions on the build host and the cross-compiled system differ in their file lists. In this case the file list is generated according to the host and not according to the sysroot.

Found during a test build on Yocto with wicked added for testing.

Handle file globbing explicitly in inst_multiple with allowing the same failure as originally if the file pattern comes up empty when resolving.

Fixed modules that were using file globbing with inst_multiple: 35network-wicked, 90kernel-modules, 90nvdimm, 95fcoe, 95udev-rules

## Changes

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-02-01 13:42 UTC, haraldh commented
Good point.. I would rather solve the problem with `dracut_install` accepting a file glob option and let `dracut_install` do the globbing with the sysroot.

2021-02-01 14:02 UTC, zboszor commented
Thanks. I will look into modifying dracut-install.

2021-02-02 10:02 UTC, johannbg commented
The scope of the commit message should be the module name (without numbers) so please remove that.

2021-02-02 10:19 UTC, zboszor commented
> The scope of the commit message should be the module name (without numbers) so please remove that.

Fixed.

2021-02-08 14:04 UTC, johannbg requested changes
Could you squash the commits together

2021-02-08 14:52 UTC, zboszor commented
> Could you squash the commits together

Which ones? All of them into a single one or per-topic?

2021-02-08 15:05 UTC, johannbg commented
> > Could you squash the commits together
> 
> Which ones? All of them into a single one or per-topic?

One per topic.

2021-02-08 15:23 UTC, johannbg approved these changes
LGTM

2021-02-08 22:06 UTC, danimo approved these changes

2021-02-08 22:59 UTC, danimo commented
@zboszor Can you fix the conflict? `modules.d/06dbus/module-setup.sh` is gone and its replacement files do not need the patches.

2021-02-09 04:49 UTC, zboszor commented
> @zboszor Can you fix the conflict? `modules.d/06dbus/module-setup.sh` is gone and its replacement files do not need the patches.

Done.

2021-02-09 05:03 UTC, zboszor commented
> > @zboszor Can you fix the conflict? `modules.d/06dbus/module-setup.sh` is gone and its replacement files do not need the patches.
> 
> Done.

It's not quite true that the replacement module (06dbus-daemon) didn't need changes. It was still getting the dbus/messagebus UID/GID from the host instead of the sysroot.

2021-02-09 07:09 UTC, merged