feat(systemd-coredump): introducing systemd-coredump module
dracutdevs/dracut pull request #1042
Opened 2021-02-01 11:45 UTC by johannbg

This pull request introduces the systemd-coredump module and adds a missing global variable ( systemdutilconfdir )

2021-02-01 13:35 UTC, haraldh requested changes

2021-02-01 13:35 UTC, haraldh commented on dracut.sh
> +    systemdntpunitsconfdir systemdsystemunitdir systemdsystemconfdir \
are there some spaces missing?

2021-02-01 13:39 UTC, johannbg commented on dracut.sh
> +    systemdntpunitsconfdir systemdsystemunitdir systemdsystemconfdir \
Yep well spotted, fixed.

2021-02-01 13:49 UTC, haraldh commented on modules.d/01systemd-coredump/module-setup.sh
> +        fi
nitpicking about the indention... is this mixed tabs and spaces? Or why is the `if` block not in line with `inst_multiple`?

2021-02-01 14:03 UTC, johannbg commented
There is no particular reason for this other than it looked good in the eyes of the beholder at the time of writing :smile: but this indeed is more cosmetically correct as you mention. Note that I will need to fix this cosmetic issue probably in the other modules as well.

2021-02-01 14:06 UTC, haraldh commented
would you mind squashing the fix commits to the commits introducing the errors?

2021-02-02 17:07 UTC, danimo commented
@haraldh can you acknowledge the changes?

2021-02-02 17:08 UTC, haraldh commented
the commit message is still bogus

2021-02-02 17:56 UTC, johannbg commented
@haraldh admittedly not perfect but good enough no?

2021-02-02 17:57 UTC, haraldh approved these changes

2021-02-02 18:01 UTC, merged