Fix "watchdog-modules: numeric argument required"
dracutdevs/dracut pull request #1043
Opened 2021-02-02 03:20 UTC by Peter-Levine

Fix error `/usr/lib/dracut/modules.d/04watchdog/module-setup.sh: line 10: return: watchdog-modules: numeric argument required`.

2021-02-02 08:18 UTC, johannbg requested changes
You are missing a "return 0" to include the dependent systemd module in the initramfs. 
Also remove the "" surrounding the module.

A typical depend section should look like this.

```
depends() {
    # This module has external dependency on the <module-name> module.
    echo <module-name>
    # Return 0 to include the dependent <module-name> module in the initramfs.
    return 0
}
```

2021-02-02 09:53 UTC, johannbg commented
We also do not include the module number, just the module name in the commit message so please fix that.

2021-02-02 19:07 UTC, johannbg commented
@Peter-Levine you forgot to rebase your branch

2021-02-02 19:08 UTC, johannbg approved these changes

2021-02-03 11:19 UTC, haraldh approved these changes

2021-02-03 11:20 UTC, danimo approved these changes

2021-02-03 12:23 UTC, merged