feat(dbus,dbus-broker,dbus-daemon: Introducing dbus,dbus-broker,dbus-daemon.
dracutdevs/dracut pull request #1046
Opened 2021-02-03 16:23 UTC by johannbg

This pull request introduces 00dbus a meta dbus module which is required to manage multiple dbus implementation under the same name (dbus).
It also introduces dbus-broker which aim is to provide high performance and reliability, while keeping compatibility to the D-Bus reference implementation as well as rework of the previous 06dbus implementations as a new module under 06dbus-daemon. 
These should complete the dbus implementation in dracut..
Closes #1044, #1019, #1025, #1026

2021-02-04 12:40 UTC, haraldh commented
could you add relevant changes in `dracut.spec` for test 99 to succeed?

2021-02-04 13:19 UTC, johannbg commented
@haraldh added. 

One point we probably should remove that test in the future and or somehow improve it since a) it is prone to cause merge conflicts ( which is why I stopped adding changes to the spec files to my module PR's ) and b) expecting contributors in any shape or form to be experts in downstream packaging solutions on top of the component they are contributing to, acts as an barrier of entry to contribution and or altogether prevents them from contributing.

2021-02-05 12:29 UTC, haraldh approved these changes

2021-02-08 16:54 UTC, danimo requested changes

2021-02-08 16:54 UTC, danimo commented on modules.d/00dbus/module-setup.sh
> +            dbus="$module"
$dbus is not being `echo`'ed?

2021-02-08 17:06 UTC, johannbg commented on modules.d/00dbus/module-setup.sh
> +            dbus="$module"
Fixed

2021-02-08 17:24 UTC, danimo approved these changes

2021-02-08 19:18 UTC, merged