skip empty modalias files in drm module setup
dracutdevs/dracut pull request #1096
Opened 2021-02-13 20:47 UTC by evgeni

## Changes

## Changes

on my system (ThinkPad X201s) I have several modalias entries that are
empty:

    /sys/bus/platform/devices/dock.0/modalias
    /sys/bus/platform/devices/dock.1/modalias
    /sys/bus/platform/devices/dock.2/modalias

executing the drm module setup thus results in the following errors

    dracut-install: No SOURCE argument given

when calling dracut_instmods and hostonly mode is enabled.

Skip those entries, as there are no modules to load in this case
anyways.

Note: it is not sufficient to use [['s -s test (file size is greater
than zero), as all those files are 4096B if you stat them.

## Checklist
- [X] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes https://bugs.debian.org/982146

2021-02-13 20:57 UTC, evgeni commented on modules.d/50drm/module-setup.sh
> +            [[ -e $i && -n $(<"$i") ]] || continue
technically, the `-e` is not required, as the `for i in <wildcard>` will already return only existing things, and `-e` doesn't test the file for anything else.

2021-02-14 06:14 UTC, johannbg approved these changes

2021-02-15 15:44 UTC, haraldh requested changes

2021-02-15 15:44 UTC, haraldh commented on modules.d/50drm/module-setup.sh
> +            [[ -e $i && -n $(<"$i") ]] || continue
```suggestion
            [[ -e $i ]] || continue
            [[ -n $(<"$i") ]] || continue
```

2021-02-21 08:50 UTC, evgeni commented on modules.d/50drm/module-setup.sh
> +            [[ -e $i && -n $(<"$i") ]] || continue
done!

2021-02-22 13:55 UTC, haraldh approved these changes

2021-02-22 13:55 UTC, merged