Unfreeze /boot on exit
dracutdevs/dracut pull request #1121
Opened 2021-02-19 22:16 UTC by tsipa

If SIGWHATEVER will be processed after fsfreeze -f, but before fsfreeze
-u we will end up with /boot/ never unfrozen, let's try to minimize risk of this.

This pull request changes...

## Changes
Adds cleanup of freeze on exit.

## Checklist
- [ V ] I have tested it locally
Yes, i added `sleep 999` between `fsfreeze -f` and `fsfreeze -u` and did `kill`. Prior to fix result was - boot is frozen, after the fix - boot is fine.
- [ X ] I have reviewed and updated any documentation if relevant
I don't think it's applicalbe

- [ X ] I am providing new code and test(s) for it
I think it's not applicable.

2021-02-19 22:28 UTC, johannbg requested changes
You need fix your commit message so it passes the commisery check. Change it to  
```fix(dracut.sh): unfreeze /boot on exit``` and it should pass the check.

Note this probably wont get a full review until sometime after the weekend.

2021-02-22 13:58 UTC, haraldh requested changes

2021-02-22 13:58 UTC, haraldh commented on dracut.sh
> +    if [ "x${FSFROZEN}" != "x" ]; then
could this be?

```suggestion
    if [[ ${FSFROZEN} ]]; then
```

2021-02-22 18:02 UTC, tsipa commented on dracut.sh
> +    if [ "x${FSFROZEN}" != "x" ]; then
Done.

2021-02-23 08:05 UTC, johannbg approved these changes
LGTM

2021-02-23 08:25 UTC, haraldh approved these changes

2021-02-23 08:25 UTC, merged