fix(network-legacy): shellcheck for modules.d/35network-legacy
dracutdevs/dracut pull request #1190
Opened 2021-03-26 10:08 UTC by haraldh

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-03-29 11:40 UTC, danimo requested changes

2021-03-29 11:40 UTC, danimo commented on modules.d/35network-legacy/parse-team.sh
> +    echo "teammaster=$teammaster" > /tmp/team."${teammaster}".info
Why not `{} >` group here as well?

2021-03-29 11:45 UTC, haraldh commented on modules.d/35network-legacy/parse-team.sh
> +    echo "teammaster=$teammaster" > /tmp/team."${teammaster}".info
good point! will do

2021-03-30 08:01 UTC, haraldh commented on modules.d/35network-legacy/parse-team.sh
> +    echo "teammaster=$teammaster" > /tmp/team."${teammaster}".info
done

2021-03-30 08:13 UTC, johannbg approved these changes

2021-03-30 08:14 UTC, danimo approved these changes

2021-03-30 08:14 UTC, merged