fix(fcoe): shellcheck for modules.d/95fcoe
dracutdevs/dracut pull request #1228
Opened 2021-03-26 10:19 UTC by haraldh

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-03-26 14:08 UTC, johannbg approved these changes

2021-03-29 08:58 UTC, danimo requested changes
The removal of fcoe-genrules is more than satisfying shellcheck, right? If so, the commit message should be adjusted.

2021-03-29 11:12 UTC, haraldh commented
> The removal of fcoe-genrules is more than satisfying shellcheck, right? If so, the commit message should be adjusted.

True.. I just inserted the contents right in the calling source and since it's not called anywhere else...

2021-03-29 11:21 UTC, danimo approved these changes

2021-03-29 11:21 UTC, merged

2021-03-29 12:24 UTC, haraldh commented
hmpf... auto-merge hit