dbus-broker: enable the service
dracutdevs/dracut pull request #1280
Opened 2021-03-29 17:26 UTC by bengal

dbus-broker.service has a 'dbus.service' alias which is installed when the service gets enabled.

If the alias is not present in the initrd image, services requiring D-Bus in the initrd fail to start because they depend on dbus.service, which doesn't exist.

Therefore, enable the service to create the alias.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant

2021-03-29 20:52 UTC, johannbg requested changes
You need to fix your commit message to pass the commisery check.

Change it from
`dbus-broker: enable the service`
to
`fix(dbus-broker): enable the service`

2021-03-30 09:08 UTC, bengal commented
> You need to fix your commit message to pass the commisery check.

Done, thanks.

2021-03-30 12:11 UTC, haraldh approved these changes

2021-03-30 12:20 UTC, johannbg approved these changes

2021-03-30 12:45 UTC, merged