fix: fix word splitting issue for sed in get_ucode_file
dracutdevs/dracut pull request #1343
Opened 2021-04-09 17:03 UTC by ryncsn

This unquated regex could be splitted into two arguments and sed will
not work. I've see giving error of wrong arguments being used on my
desktop.

Signed-off-by: Kairui Song <kasong@redhat.com>

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-04-09 20:31 UTC, johannbg requested changes
You need to fix your commit message. 
Change it to 
`fix(dracut-functions): word splitting issue for sed in get_ucode_file`
otherwise LGTM

2021-04-11 19:19 UTC, ryncsn commented
Sure, fixed.

2021-04-11 22:03 UTC, thrix commented
/packit test

2021-04-12 06:18 UTC, johannbg approved these changes

2021-04-12 07:17 UTC, haraldh approved these changes

2021-04-12 07:17 UTC, merged