logger: fix logger warning during run
dracutdevs/dracut pull request #1351
Opened 2021-04-14 20:36 UTC by dustymabe

There are a bunch of `logger: unknown facility name: --user` errors
during a run. This is because logger is getting passed something like:

```
logger -p --user.info
```

Where it should be something like:

```
logger -p user.info
```

2021-04-14 20:37 UTC, dustymabe commented
cross reference with: https://github.com/coreos/fedora-coreos-tracker/issues/758

2021-04-14 20:57 UTC, dustymabe commented
let me know what the proper commit message should be? `fix(logger):` ?

2021-04-14 22:54 UTC, johannbg requested changes
Change your commit msg from

`
logger: fix logger warning during run 
`
to
`
fix(dracut-logger.sh):  double dash trigger unknown logger warnings during run
`
Did you test your fix btw?

2021-04-15 03:03 UTC, dustymabe commented
> Change your commit msg from
> 
> `logger: fix logger warning during run `
> to
> `fix(dracut-logger.sh): double dash trigger unknown logger warnings during run`

Done

> Did you test your fix btw?

I did verify in a local build the many `logger: unknown facility name: --user` went away for me. Though I'm always second guessing myself if I actually test things good enough.

2021-04-15 06:50 UTC, johannbg approved these changes

2021-04-15 10:58 UTC, haraldh approved these changes

2021-04-15 10:58 UTC, merged