fix(img-lib): Fixed the "ignored null byte in input" issue
dracutdevs/dracut pull request #1379
Opened 2021-04-21 22:21 UTC by lveyde

The system currently throws numerous nasty warning messages during
the boot, about ignored null bytes in input.

This patch adds a filter to the dd command, to filter these null
bytes out, and thus to prevent these warning messages.

Signed-off-by: Lev Veyde <lveyde@redhat.com>

This pull request changes...

## Changes

## Checklist
- [V] I have tested it locally

Fixes #
This patch fixes the warning messages about the "ignored null byte in input" during the boot.

2021-04-21 22:23 UTC, lveyde commented
![Screenshot_lveyde-rhvh-4 4-210202_2021-04-21_23:40:31](https://user-images.githubusercontent.com/19437747/115628445-50c43080-a309-11eb-8664-4d175e8491ff.png)

2021-04-21 22:27 UTC, lveyde commented
That warning comes from a system with img-lib.sh with the following (relevant) content:

#!/bin/sh
# img-lib.sh: utilities for dealing with archives and filesystem images.
#
# TODO: identify/unpack rpm, deb, maybe others?


# super-simple "file" that only identifies archives.
# works with stdin if $1 is not set.
det_archive() {
    # NOTE: echo -e works in ash and bash, but not dash
    local bz="BZh" xz="$(echo -e '\xfd7zXZ')" gz="$(echo -e '\x1f\x8b')" zs="$(echo -e '\x28\xB5\x2F\xFD')"
    **local headerblock="$(dd ${1:+if=$1} bs=262 count=1 2>/dev/null)"**
    case "$headerblock" in
        $xz*) echo "xz" ;;
        $gz*) echo "gzip" ;;
        $bz*) echo "bzip2" ;;
        $zs*) echo "zstd" ;;
        07070*) echo "cpio" ;;
        *ustar) echo "tar" ;;
    esac
}

2021-04-21 22:46 UTC, johannbg commented
@lveyde you need to fix your commit message.
Change it from
`fix(img-lib): Fixed the "ignored null byte in input" issue`
to
`fix(img-lib): ignored null byte in input`

2021-04-21 22:52 UTC, lveyde commented
> @lveyde you need to fix your commit message.
> Change it from
> `fix(img-lib): Fixed the "ignored null byte in input" issue`
> to
> `fix(img-lib): ignored null byte in input`

Thanks.
Done, but IMHO there was/is too much energy wasted on getting the "right" commit message.
That is really the first project I had to fight to get the commit title "right" to have it pass the "CI" tests.

2021-04-21 23:23 UTC, johannbg approved these changes
LGTM

2021-04-22 05:44 UTC, sandrobonazzola approved these changes
/lgtm

2021-04-22 07:45 UTC, haraldh commented
Please extend the PR with:
```diff
diff --git a/modules.d/99img-lib/module-setup.sh b/modules.d/99img-lib/module-setup.sh
index 61c11038..558a9256 100755
--- a/modules.d/99img-lib/module-setup.sh
+++ b/modules.d/99img-lib/module-setup.sh
@@ -3,7 +3,7 @@
 
 # called by dracut
 check() {
-    require_binaries tar gzip dd echo || return 1
+    require_binaries tar gzip dd echo tr || return 1
     return 255
 }
 
@@ -14,7 +14,7 @@ depends() {
 
 # called by dracut
 install() {
-    inst_multiple tar gzip dd echo
+    inst_multiple tar gzip dd echo tr
     # TODO: make this conditional on a cmdline flag / config option
     inst_multiple -o cpio xz bzip2 zstd
     inst_simple "$moddir/img-lib.sh" "/lib/img-lib.sh"

```

2021-04-22 07:46 UTC, haraldh requested changes
Please extend the PR with:
```diff
diff --git a/modules.d/99img-lib/module-setup.sh b/modules.d/99img-lib/module-setup.sh
index 61c11038..558a9256 100755
--- a/modules.d/99img-lib/module-setup.sh
+++ b/modules.d/99img-lib/module-setup.sh
@@ -3,7 +3,7 @@
 
 # called by dracut
 check() {
-    require_binaries tar gzip dd echo || return 1
+    require_binaries tar gzip dd echo tr || return 1
     return 255
 }
 
@@ -14,7 +14,7 @@ depends() {
 
 # called by dracut
 install() {
-    inst_multiple tar gzip dd echo
+    inst_multiple tar gzip dd echo tr
     # TODO: make this conditional on a cmdline flag / config option
     inst_multiple -o cpio xz bzip2 zstd
     inst_simple "$moddir/img-lib.sh" "/lib/img-lib.sh"

```

2021-04-22 08:42 UTC, lveyde commented
> Please extend the PR with:
> 
> ```diff
> diff --git a/modules.d/99img-lib/module-setup.sh b/modules.d/99img-lib/module-setup.sh
> index 61c11038..558a9256 100755
> --- a/modules.d/99img-lib/module-setup.sh
> +++ b/modules.d/99img-lib/module-setup.sh
> @@ -3,7 +3,7 @@
>  
>  # called by dracut
>  check() {
> -    require_binaries tar gzip dd echo || return 1
> +    require_binaries tar gzip dd echo tr || return 1
>      return 255
>  }
>  
> @@ -14,7 +14,7 @@ depends() {
>  
>  # called by dracut
>  install() {
> -    inst_multiple tar gzip dd echo
> +    inst_multiple tar gzip dd echo tr
>      # TODO: make this conditional on a cmdline flag / config option
>      inst_multiple -o cpio xz bzip2 zstd
>      inst_simple "$moddir/img-lib.sh" "/lib/img-lib.sh"
> ```

Done.

2021-04-22 08:52 UTC, haraldh approved these changes

2021-04-22 09:23 UTC, merged

2021-04-22 10:57 UTC, lveyde commented
Opened a RHBZ to track the issue: https://bugzilla.redhat.com/show_bug.cgi?id=1952400