98integrity: Properly set up EVM when using an x509 cert
dracutdevs/dracut pull request #1416
Opened 2021-04-30 15:32 UTC by stefanberger

The current EVM script does not handle the EVM setup properly when X509
certificates are involved. In this patch we extend the setup and add
the necessary flags for support of EVM activation that include
x509 certificates, possibly in conjunction with an HMAC key. We also
first try activating EVM for x509 certificates using
EVM_ALLOW_METADATA_WRITES for newer kernels, then without it for older
ones that did not support this flag.

We add support for additional EVM activation bits to be set, such
as EVM_SETUP_COMPLETE (0x80000000) via the config file and
EVM_ACTIVATION_BITS variable.

To avoid error messages related to unloading the HMAC key if none is
used, only attempt to unload the HMAC key if one was actually set.

We add documentation about the variables that can be set in the EVM
config file.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
Reviewed-by: Mimi Zohar <zohar@linux.ibm.com>
Cc: Roberto Sassu <roberto.sassu@huawei.com>

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-04-30 16:51 UTC, johannbg requested changes
Minor nitpick we don't include module numbers in commit messages since those can be subjected to changes so change your commit msg from 
`fix(98integrity): Properly set up EVM when using an x509 cert` 
to  
`fix(integrity): Properly set up EVM when using an x509 cert` 
other than that LGTM.

2021-04-30 17:36 UTC, stefanberger commented
> Minor nitpick we don't include module numbers in commit messages since those can be subjected to changes so change your commit msg from
> `fix(98integrity): Properly set up EVM when using an x509 cert`
> to
> `fix(integrity): Properly set up EVM when using an x509 cert`
> other than that LGTM.

Fixed and pushed again to entertain the ci/cd a bit more.

2021-04-30 17:53 UTC, johannbg approved these changes

2021-05-03 08:13 UTC, haraldh approved these changes

2021-05-03 08:13 UTC, merged