fix(dash): minor cleanups
dracutdevs/dracut pull request #1503
Opened 2021-05-18 13:23 UTC by johannbg

- Remove hard coded path to binary
- Add missing license header
- Document sections
- refactor install section

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-05-19 08:57 UTC, haraldh requested changes

2021-05-19 08:57 UTC, haraldh commented on modules.d/00dash/module-setup.sh
> +    [[ -L $initdir/bin/sh ]] || ln -sf dash "${initdir}/bin/sh"
If `dash` is not installed in the same directory as `"${initdir}/bin/sh"`, then `ln -sf dash "${initdir}/bin/sh"` will break the initramfs.

2021-05-19 10:04 UTC, haraldh approved these changes

2021-05-25 11:59 UTC, danimo approved these changes

2021-05-25 11:59 UTC, merged