fix install fsck programs
dracutdevs/dracut pull request #1514
Opened 2021-05-22 10:02 UTC by tpgxyz

This pull requestfixes the installation of fsck programs which got broken by this commit https://github.com/dracutdevs/dracut/commit/82d9fbf193b0d8bd810c6cbee726a1f851e5ee75#diff-52b92d069b8698c8b6332b0357d1ffe1bec3f07f4a23406a3c697f11d2cb10ce

## Changes

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-05-22 11:05 UTC, haraldh approved these changes

2021-05-23 13:42 UTC, tpgxyz commented
@haraldh @danimo @johannbg Guys i think this is quite important. Bu releaseing 054 many users after update and initrd regeneration may end up with not bootable system, because of missing fsck utilities. I guess some may handle that incovience, but i'd suggest to merge this PR and release new version of dracut.

2021-05-23 15:29 UTC, johannbg requested changes
You need to fix your commit msg
from
`fix install fsck utilities`
to
fix(fs-lib): install fsck utilities

2021-05-24 08:13 UTC, tpgxyz commented
@johannbg done

2021-05-25 09:28 UTC, haraldh requested changes

2021-05-25 09:28 UTC, haraldh commented on modules.d/99fs-lib/module-setup.sh
> +    inst_multiple -o $_helpers fsck
```suggestion
    # shellcheck disable=SC2086
    inst_multiple -o $_helpers fsck
```

2021-05-25 09:41 UTC, haraldh commented
I even would suggest this version:
```bash
# called by dracut
install() {
    local _helpers

    inst "$moddir/fs-lib.sh" "/lib/fs-lib.sh"
    : > "${initdir}"/etc/fstab.empty

    [[ $nofscks == "yes" ]] && return

    if [[ $fscks == "${fscks#*[^ ]*}" ]]; then
        _helpers=(
            /sbin/fsck* /usr/sbin/fsck*
            xfs_db xfs_check xfs_repair xfs_metadump
            e2fsck jfs_fsck reiserfsck btrfsck
        )
        if [[ $hostonly ]]; then
            read -r -a _helpers < <(for_each_host_dev_fs echo_fs_helper)
        fi
    else
        read -r -a _helpers <<< "$fscks"
    fi

    _helpers+=(umount mount)

    if [[ ${_helpers[*]} == *e2fsck* ]] && [[ -e $dracutsysrootdir/etc/e2fsck.conf ]]; then
        inst_simple /etc/e2fsck.conf
    fi

    inst_multiple -o "${_helpers[@]}" fsck
}
```

2021-05-25 11:46 UTC, tpgxyz commented
>     inst_multiple -o "${_helpers[@]}" fsck

Thanks for the hint... how could i forget about using it :<

2021-05-26 07:12 UTC, haraldh approved these changes

2021-05-26 07:14 UTC, haraldh requested changes

2021-05-26 07:14 UTC, haraldh commented on modules.d/99fs-lib/module-setup.sh
>      if [[ $_helpers == *e2fsck* ]] && [[ -e $dracutsysrootdir/etc/e2fsck.conf ]]; then
```suggestion
    if [[ ${_helpers[*]} == *e2fsck* ]] && [[ -e $dracutsysrootdir/etc/e2fsck.conf ]]; then
```

2021-05-26 18:05 UTC, tpgxyz commented on modules.d/99fs-lib/module-setup.sh
>      if [[ $_helpers == *e2fsck* ]] && [[ -e $dracutsysrootdir/etc/e2fsck.conf ]]; then
fixed

2021-05-26 18:12 UTC, johannbg approved these changes

2021-05-27 07:12 UTC, haraldh approved these changes

2021-05-27 07:13 UTC, merged