tpm2-tss module: fix typo in depends()
dracutdevs/dracut pull request #1526
Opened 2021-06-01 17:34 UTC by mberndt123

There is no systemd-udev module to depend on, because the module is called systemd-udevd.

2021-06-01 17:53 UTC, johannbg requested changes
You need to fix your commit msg. 
Change it 
from 
`tpm2-tss module: fix typo in depends()`
to 
`fix(tpm2-tss): typo in depends()`

2021-06-01 19:04 UTC, mberndt123 commented
yeah, whatever.

2021-06-01 20:23 UTC, johannbg commented
> yeah, whatever.

Does this respond mean you plan on fixing it or does it mean you plan not to fix it?

2021-06-01 20:42 UTC, mberndt123 commented
> Does this respond mean you plan on fixing it or does it mean you plan not to fix it?

I means I've already fixed it.

2021-06-01 20:50 UTC, johannbg approved these changes

2021-06-22 13:32 UTC, haraldh approved these changes

2021-06-22 13:32 UTC, merged

2024-06-16 09:09 UTC, SoumyadipYT-OSS commented
In my Garuda Linux:
darcut[E]: Module 'systemd-pcrphase' depends on 'tpm2-tss' which can't be installed. During installation my nvidia version on arch linux distro(Garuda Linux Xfce). Can anybody solve this problem.

2024-06-24 14:49 UTC, TheOverpassArsonist commented
I'm also on Garuda and having the same issue as Soumyadlip but I'm not sure if it's related to this issue/merge at all since this appears to have been resolved years ago and has a different (though quite similar) error.