nvmf: fix validate_ip_conn
dracutdevs/dracut pull request #1541
Opened 2021-06-18 17:51 UTC by charles-rose

1. ifname should be the interface on which $traddr can be reached. It currently gets set to "lo", which is incorrect. This patch identifies the correct interface that would be used for the nvme-of-tcp connection.
2. 'ip l show' and 'ip route get' both succeed if interface and route are present. Current 'if' condition (wrongly) produces a warning when the commands succed. This patch fixes that.

Signed-off-by: Charles Rose <charles.rose@dell.com>

This pull request changes...

## Changes
- fix ifname and route check for nvmf tcp connections.

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-06-25 19:28 UTC, johannbg requested changes
You need to fix your commit msg.
Change it 
from 
`nvmf: fix validate_ip_conn`
to 
`fix(nvmf): validate_ip_conn`

2021-06-25 21:26 UTC, johannbg commented
@charles-rose you need to fix the commit message itself not the title of the pull request.

2021-06-28 11:23 UTC, haraldh approved these changes

2021-06-30 17:53 UTC, charles-rose commented
> 
> 
> @charles-rose you need to fix the commit message itself not the title of the pull request.
Thank you for the review @johannbg
Should I create a new pull request with the amended commit?

2021-07-01 07:53 UTC, haraldh commented
No, just force push a corrected version to your PR branch.

2021-08-07 09:09 UTC, closed without merging