fix(integrity): Add support for loading multiple EVM x509 certs
dracutdevs/dracut pull request #1546
Opened 2021-06-23 18:08 UTC by stefanberger

Add support for loading EVM x509 certs from a directory that the user can
specify with the EVMKEYSDIR variable in the evm config file. By default
the additional certs are loaded from /etc/keys/evm.

Support for multiple EVM keys allows the usage in a system of files with
signed metadata from multiple parties.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
Reviewed-by: Roberto Sassu <roberto.sassu@huawei.com>

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-06-25 19:10 UTC, johannbg approved these changes
LGTM

2021-06-28 11:28 UTC, haraldh requested changes

2021-06-28 11:28 UTC, haraldh commented on modules.d/98integrity/evm-enable.sh
> +    for PUBKEY in ${EVMX509PATH} ${PUBKEY_LIST}; do
```suggestion
    for PUBKEY in ${EVMX509PATH} "${NEWROOT}"${EVMKEYSDIR}/*; do
```

2021-06-28 14:08 UTC, stefanberger commented on modules.d/98integrity/evm-enable.sh
> +    for PUBKEY in ${EVMX509PATH} ${PUBKEY_LIST}; do
Done.

2021-07-13 22:38 UTC, stefanberger commented
@haraldh Did I address your change request sufficiently?

2021-08-06 13:58 UTC, haraldh approved these changes

2021-08-06 13:58 UTC, merged