Enhance Emergency Shell
dracutdevs/dracut pull request #1555
Opened 2021-07-05 07:59 UTC by wtmpx

Dears, Dracut emergency shell looks similar to Systemd emergency shell: 

[ OK ] Started Tell Plymouth To Write Out Runtime Data.
You are in emergency mode. After logging in, type "journalctl -xb" to view
system logs, "systemctl reboot" to reboot, "systemctl default" or ^D to boot
into default mode.
Give root password for maintenance
(or press Control-D to continue):

---- 

Please print, Entering dracut emergency shell.

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-07-05 14:11 UTC, haraldh approved these changes

2021-07-07 15:02 UTC, haraldh commented
Please change your git commit title to something like:
```
fix(emergency): clarify that emergency shell is provided by dracut
```

2021-07-07 15:19 UTC, wtmpx commented
I updated the title, you are correct, it was not clear.

2021-07-07 15:38 UTC, haraldh commented
I mean the real git commit.. not the github PR title.

2021-07-08 20:34 UTC, johannbg requested changes
You need to fix your commit msg to match your title description.
Other than that LGTM

2021-07-09 14:01 UTC, haraldh commented
and you'll need to force push your fixed message

2021-07-09 15:46 UTC, wtmpx commented
> and you'll need to force push your fixed message

Is it now okay?

2021-07-09 15:53 UTC, haraldh commented
https://github.com/wtmpx/dracut/tree/patch-1 does not contain the fixed message

2021-07-09 15:53 UTC, haraldh commented
wrong branch

2021-07-09 15:56 UTC, wtmpx commented
Sorry, I created new commit: 
Print Entering dracut emergency mode instade of Entering emergency mode #1559

2021-07-09 15:56 UTC, closed without merging

2021-07-09 15:57 UTC, haraldh commented
Why?

2021-07-09 15:58 UTC, haraldh commented
you could have just changed to the correct branch and pushed from there