90kernel-modules: Add more modules on RISC-V
dracutdevs/dracut pull request #1556
Opened 2021-07-08 18:08 UTC by andreas-schwab

Include the same extra modules for ARM also on RISC-V and add drivers/mmc/host
and drivers/spi to the list.

2021-07-08 20:32 UTC, johannbg requested changes
You need to change your commit msg
from
`fix(kernel-modules): Add more modules on RISC-V`
to
`fix(kernel-modules): add more modules on RISC-V`
to pass the commisery check.

Other than that LGTM

2021-07-17 08:30 UTC, johannbg approved these changes

2021-07-20 18:58 UTC, johannbg commented
@haraldh ping

2021-07-21 15:09 UTC, haraldh approved these changes

2021-07-21 15:10 UTC, merged