fix(kernel-modules): go downstream block device's hardware stack to d…
dracutdevs/dracut pull request #1571
Opened 2021-07-29 02:53 UTC by pfliu

…etect driver

On hostonly mode, the platform driver is not copied blindless. There
should be a way to detect the real hardware driver, which probes a block
device.

/sys/dev/block/major:minor is a symbol link, which points to the real
device, recording the hardware stack. And those info can help to
identify the associated drivers.

Signed-off-by: Pingfan Liu <piliu@redhat.com>

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-07-29 09:00 UTC, pfliu commented
I hit this bug at an arm64 machine, which requires ahci_platform.ko to probe block device.

[root@ampere-hr330a-01 ~]# cd /sys/dev/block/
[root@ampere-hr330a-01 block]# ls
11:0  253:0  253:1  253:2  8:0  8:1  8:16  8:2  8:3
[root@ampere-hr330a-01 block]# realpath 8:3
/sys/devices/platform/APMC0D33:00/ata1/host1/target1:0:0/1:0:0:0/block/sda/sda3
[root@ampere-hr330a-01 block]# ls /sys/devices/platform/APMC0D33:00/
ata1  ata2  driver  driver_override  firmware_node  iommu  iommu_group  modalias  power  subsystem  supplier:platform:arm-smmu.1.auto  uevent
[root@ampere-hr330a-01 block]# realpath /sys/devices/platform/APMC0D33:00/driver/module
/sys/module/ahci_platform

2021-08-06 13:46 UTC, haraldh requested changes
your git commit message is one char too long :)

2021-08-06 13:46 UTC, haraldh commented on modules.d/90kernel-modules/module-setup.sh
> +        local _extra_mod
why use an extra variable here?

2021-08-06 13:46 UTC, haraldh commented on modules.d/90kernel-modules/module-setup.sh
> +        for _mod in $_extra_mod; do
```suggestion
        for _mod in $(get_blockdev_drv_through_sys "/sys/dev/block/$1"); do
```

2021-08-11 10:23 UTC, pfliu commented
> your git commit message is one char too long :)

Do you mean the subject line is too long?  I fail to find any hint in docs/HACKING.md in a quick through.

Anyway, I shorten the subject in the new version.

Most of all, thanks for your review.

2021-08-11 10:38 UTC, haraldh requested changes
```
----------

In dracut-functions.sh line 624:
    local _path=$(realpath $1)
          ^---^ SC2155: Declare and assign separately to avoid masking return values.
                           ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    local _path=$(realpath "$1")


In dracut-functions.sh line 628:
            _mod=$(realpath $_path/driver/module)
                            ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
            _mod=$(realpath "$_path"/driver/module)


In dracut-functions.sh line 629:
            _mod=$(basename $_mod)
                            ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
            _mod=$(basename "$_mod")


In dracut-functions.sh line 632:
        _path=$(dirname $_path)
                        ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
        _path=$(dirname "$_path")


In dracut-functions.sh line 637:
    echo $_block_mods
         ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    echo "$_block_mods"
```

2021-08-11 12:29 UTC, pfliu commented
> ```
> ----------
> 
> In dracut-functions.sh line 624:
>     local _path=$(realpath $1)
>           ^---^ SC2155: Declare and assign separately to avoid masking return values.
>                            ^-- SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean: 
>     local _path=$(realpath "$1")
> 
> 
> In dracut-functions.sh line 628:
>             _mod=$(realpath $_path/driver/module)
>                             ^----^ SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean: 
>             _mod=$(realpath "$_path"/driver/module)
> 
> 
> In dracut-functions.sh line 629:
>             _mod=$(basename $_mod)
>                             ^---^ SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean: 
>             _mod=$(basename "$_mod")
> 
> 
> In dracut-functions.sh line 632:
>         _path=$(dirname $_path)
>                         ^----^ SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean: 
>         _path=$(dirname "$_path")
> 
> 
> In dracut-functions.sh line 637:
>     echo $_block_mods
>          ^----------^ SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean: 
>     echo "$_block_mods"
> ```

Address all of the shell check issue in V3

Thank you very much

2021-08-11 20:43 UTC, johannbg approved these changes

2021-08-13 11:36 UTC, haraldh approved these changes

2021-08-13 11:36 UTC, merged