Minor fixes on `95suspend` and `99base`
dracutdevs/dracut pull request #1607
Opened 2021-09-17 22:19 UTC by jmfernandez

This pull request fixes `95suspend` module and a function from `99base`, so resumes from hibernation using https://github.com/bircoph/suspend work in Gentoo.

## Changes

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #
- `95suspend` module setup now also searches for /usr/lib64/suspend/resume and /usr/lib64/uswsusp/resume , which are relevant on distros like Gentoo.
- `label_uuid_to_dev` now returns the unaltered input when it does not match any of the alternate ways to designate a device. Previously, the function was returning nothing, leading to potential failures in several places.

2021-11-08 20:07 UTC, johannbg requested changes
You need to rephrase your commit messages description field to not exceed line a length of 80 as well as not to use a title case in the description.

2021-11-23 06:09 UTC, johannbg commented
@jmfernandez hmm commisery is still unhappy. 
change this commit msg 
from
`fix(base): added default device choice`
to
`fix(base): add default device choice`

2021-11-23 10:21 UTC, jmfernandez commented
> @jmfernandez hmm commisery is still unhappy. change this commit msg from `fix(base): added default device choice` to `fix(base): add default device choice`

Just done

2021-11-24 12:17 UTC, johannbg approved these changes

2021-11-24 12:17 UTC, merged