feat(dracut.sh): fix for check if kernel has zstd support
dracutdevs/dracut pull request #1609
Opened 2021-09-20 17:00 UTC by tpgxyz

This pull request changes... in compression logic

## Changes

## Checklist
- [X ] I have tested it locally
- [ ]X I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes commit https://github.com/dracutdevs/dracut/commit/591118c56da2bfcea060e3b7671bc87b23c0e44a

In my opinion something went wrong in PR review process:
- why introduce external check for zstd in-kernel support
- why zstd support in kernel must be checked now? Why nobody bother for gz/bzip2/lz4/others by following this logic? Does zstd is some kind of special one ?

2021-09-21 07:43 UTC, aafeijoo-suse commented
@tpgxyz I don't agree with this change, because it would only perform the check if `$compress` has no parameters, to set the defaults.

> why zstd support in kernel must be checked now? Why nobody bother for gz/bzip2/lz4/others by following this logic? Does zstd is some kind of special one ?

I think you are right and it would be nice to check if the kernel is configured with the compression option selected... but it's out of the scope of this request.

2021-09-21 08:30 UTC, tpgxyz commented
@aafeijoo-suse if nobody set "default" compression then it means:
1. lousy maitenace/packaging
2. done o purpose

2021-09-22 13:12 UTC, ddiss approved these changes
This looks fine to me. I agree that it makes sense to cover other compression types, but they can be done separately.

2021-11-07 10:48 UTC, johannbg requested changes
A commit msg cannot be both a feature and a fix so can you change it 
from
`feat(dracut.sh): fix for check if kernel has zstd support`
to
`fix(dracut.sh): check if kernel has zstd support`

Otherwise LGTM

2021-11-10 12:09 UTC, tpgxyz commented
@johannbg thanks for the review, i applied your requested changes.

2021-11-10 18:59 UTC, johannbg approved these changes

2021-11-24 10:00 UTC, haraldh commented
Thanks for your contribution.
I think I am in favor of https://github.com/dracutdevs/dracut/pull/1646 ... Please review that one!

2021-11-24 10:21 UTC, tpgxyz commented
@haraldh Thanks, i already posted my 3 cents there.

2021-11-24 10:21 UTC, closed without merging