fix(90mdraid): allow UUID comparison for more than one UUID
dracutdevs/dracut pull request #1633
Opened 2021-11-02 10:06 UTC by qby-wenzel

If the system provides more than one UUID, the __MD_UUID_ var contains a [line break](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/dracut-lib.sh#L315) after each UUID. Therefore the [strstr](https://github.com/dracutdevs/dracut/blob/master/modules.d/99base/dracut-lib.sh#L31)
function could not find any UUID, caused by the additional spaces provided to the function.

Furthermore this could lead to a boot interruption, because the start of a degraded raid1 won't be executed. So, manual
interaction is necessary.

**Scenario**:
System with two raid1 (md0+md1) partitions. One disk fails and system tries to boot:

- udev discovers raid partitions and starts to assemble them [incrementally](https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/65-md-incremental-imsm.rules#L42)
- both raid partitions stay degraded because second disk is missing
- rd.retry timeout kicks in and [executes](https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/65-md-incremental-imsm.rules#L34) /sbin/mdraid_start
- [comparison](https://github.com/dracutdevs/dracut/blob/master/modules.d/90mdraid/mdraid_start.sh#L57) of existing UUIDs fails
- dracut timeouts and falls into emergency shell

**Simplified bugfix output**:
```
#!/bin/bash

strstr() { [[ $1 == *"$2"* ]]; }

UUID=$(printf '%s\n' AAA BBB)
TEST="BBB"

strstr " $UUID " " $TEST " || echo bug
strstr "$UUID" "$TEST" && echo fix

#########################################

++ printf '%s\n' AAA BBB
+ UUID='AAA
BBB'
+ TEST=BBB
+ strstr ' AAA
BBB ' ' BBB '
+ [[  AAA
BBB  == *\ \B\B\B\ * ]]
+ echo bug
bug
+ strstr 'AAA
BBB' BBB
+ [[ AAA
BBB == *\B\B\B* ]]
+ echo fix
fix
```

## Changes

Removed additional spaces from input of comparison function.
[Manpage](https://github.com/dracutdevs/dracut/blob/master/man/dracut.cmdline.7.asc#md-raid
) about _rd.md.uuid_ ("This parameter can be specified multiple times.") is true again ;)

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

2021-11-07 10:04 UTC, johannbg requested changes
@qby-wenzel minor nit-pick 
could you remove the module number from the commit msg as in change the commit msg 
from 
`fix(90mdraid): allow UUID comparison for more than one UUID`
to
`fix(mdraid): allow UUID comparison for more than one UUID`

We dont include those since the module numbers are subjected to change.

2021-11-08 12:45 UTC, qby-wenzel commented
@johannbg no problem, it's done.

2021-11-08 19:58 UTC, johannbg approved these changes

2021-11-24 10:07 UTC, haraldh approved these changes

2021-11-24 10:15 UTC, merged