fix(95resume) - check for presence of /sys/power/resume
dracutdevs/dracut pull request #1636
Opened 2021-11-10 11:20 UTC by sharkcz

On platforms where the kernel is built without suspend/resume support we
see "cat: /sys/power/resume: No such file or directory" message when
creating an initrd image. Check for the presence of /sys/power/resume
first before reading it.

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [N/A] I am providing new code and test(s) for it

2021-11-10 18:56 UTC, johannbg requested changes
We dont include module numbers in the description field in commit messages since those numbers are subjected to changes as well as your commit message is lacking `:` thus failing the commisery check so change your commit msg  
from
`fix(95resume) - check for presence of /sys/power/resume`
to 
fix(resume):  check for presence of /sys/power/resume

2021-11-22 19:22 UTC, johannbg commented
@sharkcz you have an excess whitespace in the description ( after fix(resume): ) in your commit msg. 
You need to fix that so the commisery test passes.

2021-11-22 20:45 UTC, sharkcz commented
oh, thanks, hopefully this time it will be OK :-)

2021-11-22 21:06 UTC, johannbg approved these changes

2021-11-24 09:56 UTC, haraldh approved these changes

2021-11-24 09:56 UTC, merged