fix(s390_rules): make collect optional
dracutdevs/dracut pull request #1645
Opened 2021-11-19 10:45 UTC by tblume

/usr/lib/udev/collect has been removed from systemd v246, so make it optional in the udev rules

This pull request changes...

dependency of s390 udev rules on collect

## Changes

## Checklist
- [X ] I have tested it locally
- [X ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-11-20 10:06 UTC, johannbg requested changes
@tblume can you update your PR to just drop it since no one should be using it anymore.

2021-11-22 08:23 UTC, tblume commented
> @tblume can you update your PR to just drop it since no one should be using it anymore.

@johannbg if we just drop collect we will bind dracut to the new chzdev generated udev rules that work without collect.
That means in turn we will make dracut somewhat dependent on newer s390-tools versions.
We might break older systems with rules that still use collect (if they have a systemd version that still ships collect).
Not sure how many systems would be concerned though.
Should we take that risk?

2021-11-22 08:31 UTC, dtardon commented on modules.d/95dasd_rules/module-setup.sh
> +    [[ -f /usr/lib/udev/collect ]] && inst_multiple /usr/lib/udev/collect
The check isn't needed. Just call `inst_multiple` with `-o`.

2021-11-22 08:31 UTC, dtardon commented on modules.d/95qeth_rules/module-setup.sh
> +    [[ -f /usr/lib/udev/collect ]] && inst_simple /usr/lib/udev/collect
Same here.

2021-11-22 08:32 UTC, dtardon commented on modules.d/95zfcp_rules/module-setup.sh
> +    [[ -f /usr/lib/udev/collect ]] && inst_multiple /usr/lib/udev/collect
Same here.

2021-11-22 08:52 UTC, johannbg commented
Well from my pov distribitions should not be shipping mix and match of versions of components that make up the core/base OS layer so distributions should never hit the scenario you describe.

If distributions choose to play that game, they should also pay the price for that madness by carrying patches for that downstream. 

Upstreams should not be working around that for them at the cost of code bloat and performance.

2021-11-22 08:56 UTC, tblume commented
> Well from my pov distribitions should not be shipping mix and match of versions of components that make up the core/base OS layer so distributions should never hit the scenario you describe.
> 
> If distributions choose to play that game, they should also pay the price for that madness by carrying patches for that downstream.
> 
> Upstreams should not be working around that for them at the cost of code bloat and performance.

ok, thanks, just wanted to make sure we do the right ting.

2021-11-22 09:00 UTC, tblume commented
We should remove that too:

-->
 grep -r collect modules.d/
modules.d/95dasd_rules/parse-dasd.sh:ACTION=="add", SUBSYSTEM=="ccw", KERNEL=="$ccw", IMPORT{program}="collect $ccw %k ${ccw} $_drv"
modules.d/95dasd_rules/parse-dasd.sh:ACTION=="add", SUBSYSTEM=="drivers", KERNEL=="$_drv", IMPORT{program}="collect $ccw %k ${ccw} $_drv"
modules.d/95zfcp_rules/parse-zfcp.sh:ACTION=="add", SUBSYSTEM=="ccw", KERNEL=="$ccw", IMPORT{program}="collect $ccw %k ${ccw} zfcp"
modules.d/95zfcp_rules/parse-zfcp.sh:ACTION=="add", SUBSYSTEM=="drivers", KERNEL=="zfcp", IMPORT{program}="collect $ccw %k ${ccw} zfcp"
--<

2021-11-22 09:38 UTC, haraldh approved these changes

2021-11-22 18:09 UTC, johannbg approved these changes
@tblume are you going to do a seperated PR's for the other removals that you pointed out?

2021-11-22 18:09 UTC, merged

2021-11-23 07:49 UTC, tblume commented
> @tblume are you going to do a seperated PR's for the other removals that you pointed out?

Yes, will do, just awaiting feedback from the original provider of the rules.