fix(dmsquash-live-ntfs): fuse3 no longer requires ulockmgr_server
dracutdevs/dracut pull request #1648
Opened 2021-11-19 21:08 UTC by LaszloGombos

fuse3 no longer includes ulockmgr_server.
https://github.com/libfuse/libfuse/blob/master/ChangeLog.rst#libfuse-300-2016-12-08

This pull request changes...

## Changes

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-11-20 10:09 UTC, johannbg requested changes
@LaszloGombos can you update your PR to just drop it instead.

2021-11-21 06:23 UTC, johannbg approved these changes

2021-11-21 22:06 UTC, thrix commented
/packit test

2021-11-22 09:40 UTC, haraldh approved these changes

2021-11-22 09:40 UTC, merged