fix(dmsquash-live): Do not install systemd dependent files when systemd is not enabled
dracutdevs/dracut pull request #1649
Opened 2021-11-19 21:20 UTC by LaszloGombos

Systemd is an optional module for the dmsquash-live module. This scenario
is properly handled for other modules (for example livenet module) but not for
dmsquash-live module.

## Changes

## Checklist
- [X] I have tested it locally
- [X] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-11-21 22:04 UTC, thrix commented
/packit test

2021-11-22 09:40 UTC, haraldh approved these changes

2021-11-22 18:07 UTC, johannbg requested changes
Can you fix your commit message so the PR passes the commisery check. 
Change the message from
`fix(dmsquash-live): Do not install systemd dependent files when systemd is not enabled`
to
`fix(dmsquash-live): do not install systemd files when systemd is not enabled`

2021-11-23 00:29 UTC, LaszloGombos commented
> Can you fix your commit message so the PR passes the commisery check. Change the message from `fix(dmsquash-live): Do not install systemd dependent files when systemd is not enabled` to `fix(dmsquash-live): do not install systemd files when systemd is not enabled`

Thanks, resolved.

2021-11-23 05:53 UTC, johannbg approved these changes

2021-11-23 05:53 UTC, merged