Add errors and warnings when network interface does not exist
dracutdevs/dracut pull request #1652
Opened 2021-11-23 17:51 UTC by pvalena

End with error, or show a warning when nonexistent device is specified for network setup like `ip=10.12.8.12::10.12.255.254:255.255.0.0:xk12:eth0:off`.

## Changes

I've added the error only for `write-ifcfg.sh`, as I think no such setup should be written. For the rest I added only warnings, as I'm not sure `$dev` is not set to something else, or it can be a non-critical error.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #1712424

## Additional
I'm new to this - this is my first issue, so I'm not entirely sure how to test this. The test suite does not work for me, locally, but I'll try to create a reproducer.

2021-11-23 18:25 UTC, johannbg requested changes
Can you change your commit message
from
`Add errors and warnings when network interface does not exist`
to
`fix(network): add errors and warnings when network interface does not exist`

can you also run `shfmt -s -w modules.d/35network-legacy/ifup.sh` to fix the formatting errors.

2021-11-24 19:25 UTC, pvalena commented
> Can you change your commit message from `Add errors and warnings when network interface does not exist` to `fix(network): add errors and warnings when network interface does not exist`
> 
> can you also run `shfmt -s -w modules.d/35network-legacy/ifup.sh` to fix the formatting errors.

Done.

2021-11-24 20:57 UTC, johannbg approved these changes

2021-11-25 08:58 UTC, haraldh approved these changes

2021-11-25 08:58 UTC, merged

2021-11-29 22:22 UTC, pvalena commented
Thanks!