fix(systemd-sysusers): Use split systemd sysuser configs
dracutdevs/dracut pull request #1659
Opened 2021-11-30 09:44 UTC by Cornelicorn

Fixes the regression introduced by https://github.com/systemd/systemd/pull/20056
As discussed in #1656 and #1657

## Changes
Include the new sysusers.d files to allow compatability with future systemd releases. Otherwise the users would be missing inside the initrd.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2021-12-01 07:11 UTC, Cornelicorn commented
Pushed a new version without Title case in the commit subject

2021-12-01 07:36 UTC, johannbg requested changes
You are missing the vendor path and have misplaced the admin/user path which belongs in the hostonly section and we need to have both as in the `"$sysusers"/foo.conf` which is the vendor path and belongs in the install() section of the module and the `"$sysusersconfdir"/foo.conf` which is the administrator override which belongs in the hostonly portion of the install() section 

So move 
`"$sysusersconfdir"/systemd-coredump.conf \`
`"$sysusersconfdir"/systemd-journal.conf \`
`"$sysusersconfdir"/systemd-network.conf \`
`"$sysusersconfdir"/systemd-resolve.conf \`
`"$sysusersconfdir"/systemd-timesync.conf \` 
to the `if [[ $hostonly ]];` portion of the modules and add the missing vendor files
`"$sysusers"/systemd-coredump.conf \`
`"$sysusers"/systemd-journal.conf \`
`"$sysusers"/systemd-network.conf \`
`"$sysusers"/systemd-resolve.conf \`
`"$sysusers"/systemd-timesync.conf \` 
to the install() section of the module.

2021-12-01 12:13 UTC, johannbg approved these changes
LGTM

2021-12-10 12:59 UTC, Conan-Kudo approved these changes

2021-12-10 12:59 UTC, merged