fix(iscsi): Remove unneeded iscsi NOP-disable code
dracutdevs/dracut pull request #1727
Opened 2022-02-24 18:23 UTC by gonzoleeman

Commit 7374943ae3d06 ("fix(iscsi): add support for the new iscsiadm
"no-wait" (-W) command") added some code to try to disable iscsi's
NOPs, since they are considered "bad" for an iscsi root disc,
but that code doesn't work because the session is already established
at this point. Open-iscsi will change so that it automatically
disables NOPs for the root disc, so this code can just go away.

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2022-02-25 00:19 UTC, johannbg requested changes
You need to change your commit msg since you have a title case in your description.
Change it
from
`fix(iscsi): Remove unneeded iscsi NOP-disable code`
to 
`fix(iscsi): remove unneeded iscsi NOP-disable code`

Other than that LGTM, 

@tblume might want to chime in on this and or ack/nack it.

2022-02-25 00:26 UTC, gonzoleeman commented
> You need to change your commit msg since you have a title case in your description. Change it from `fix(iscsi): Remove unneeded iscsi NOP-disable code` to `fix(iscsi): remove unneeded iscsi NOP-disable code`
> 
> Other than that LGTM,
> 
> @tblume might want to chime in on this and or ack/nack it.

Thank you, I didn't know about the non-upper-case convention.

Assuming all else is fine, should I modify my branch and force push it, or should I cancel this request and push a new branch?

2022-02-25 00:38 UTC, johannbg commented
Modify your branch and force push

2022-02-25 08:01 UTC, tblume commented
> @tblume might want to chime in on this and or ack/nack it.

ack

2022-02-25 16:44 UTC, gonzoleeman commented
I updated the commit message to remove upper case from the subject line, and I force-pushed the update.

2022-02-26 08:13 UTC, johannbg approved these changes

2022-02-26 08:13 UTC, merged