configure: check for SYS-gettid during configure
dracutdevs/dracut pull request #1750
Opened 2022-03-15 11:31 UTC by sshedi

Signed-off-by: Shreenidhi Shedi <sshedi@vmware.com>

This pull request changes...

## Changes
Check for SYS_gettid during configure stage

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [x] I am providing new code and test(s) for it

Fixes #

2022-03-17 21:25 UTC, johannbg requested changes
Could you change your commit msg
from
`configure: check for SYS-gettid during configure`
to
`fix(configure): check for SYS-gettid during configure`

Other than that LGTM

2022-03-18 05:52 UTC, sshedi commented
> Could you change your commit msg from `configure: check for SYS-gettid during configure` to `fix(configure): check for SYS-gettid during configure`
> 
> Other than that LGTM

Done. Thanks for the review.

2022-03-18 06:36 UTC, johannbg approved these changes

2022-03-30 11:48 UTC, sshedi commented
Hi @johannbg & @haraldh - Can we merge this PR?

2022-03-30 12:00 UTC, merged