Fix firmware loading paths
dracutdevs/dracut pull request #1794
Opened 2022-04-26 15:44 UTC by nabijaczleweli

## Changes
The firmware loading path is
1. contents of /sys/module/firmware_class/parameters/path (`fw_path_para`), if any
2. /lib/firmware/updates/$(uname -r)
3. /lib/firmware/updates
4. /lib/firmware/$(uname -r)
5. /lib/firmware

Always.

Repeated single-character strstr()s -> strpbrk() and stat()s with unused buffers -> access()es.

Also check for `.zst`-suffixed firmware, coming in 5.19: https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/driver-core.git/commit/?h=driver-core-next&id=23cfbc6ec44e5e80d5522976ff45ffcdcddfb230

62bluetooth `inst_multiple`s its firmware (for some reason?); glob at the end of the unglobbed paths to catch compressed fw.

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

2022-04-26 16:00 UTC, nabijaczleweli commented
Would appreciate guidance w.r.t. what "tags"(??) I'm supposed to put in the commit messages

2022-04-26 18:40 UTC, johannbg commented
> Would appreciate guidance w.r.t. what "tags"(??) I'm supposed to put in the commit messages

See HACKING.md in the docs directory

2022-05-05 21:00 UTC, johannbg commented
From an OS design perspective vendor-supplied operating system resources should resided within /usr and  /bin, /sbin, /lib  and be symlinks to the /usr file system

What your PR is based on seems to be the kernels firmware`s api search paths thou not technically wrong it's not what vendor ( distributions ) are/should be using so arguably it's a bug with the kernel firmware`s api search paths that it does not include searching under /usr/lib/firmware/ these days

2022-05-05 22:09 UTC, nabijaczleweli commented
Thankfully, the system has already been designed by the kernel (firmware lives in `/lib/firmware`), and distributor + local administrator (`/lib` is `/usr/lib` sometimes). On our target system (the initrd), `/lib` is `/usr/lib` always, but that doesn't matter, since that's a superset of a split-/usr system.
This is strictly a conformance issue (we *must* match the search paths and methodology *exactly* to the kernel or we may not pick up the same firmware as it has in the real root).
I don't really see your point.

2022-05-30 21:30 UTC, nabijaczleweli commented
Bumping this after a month

2022-05-30 22:08 UTC, johannbg commented
Btw this is practically an ack already, minor issues with the commit messages ( I was planning on updating the docs once I notice what you did after I responded with regards to the commit msg but have not had the time to do that nor something else ) I'm going to see if we cant sort that commit message out and any other issue that I might find and have this merged by the end of the week.

2022-06-09 10:58 UTC, aafeijoo-suse requested changes
I think you should change your commit messages by adding the affected module/part in parentheses, always avoiding using the module number, because it may change in the future. E.g. with 5ab7a78634859141103f92cd87a002f6f0ee8f20: `fix(bluetooth): accept compressed firmwares in inst_multiple`

2022-06-09 10:58 UTC, aafeijoo-suse commented on modules.d/62bluetooth/module-setup.sh
> +        /lib/firmware/ath3k-1.fw \
Missing * here, it should be `/lib/firmware/ath3k-1.fw*`

2022-06-09 10:58 UTC, aafeijoo-suse commented on modules.d/62bluetooth/module-setup.sh
> +        /lib/firmware/brcm/*.hcd \
Missing * here, it should be `/lib/firmware/brcm/*.hcd*`

2022-06-09 13:15 UTC, nabijaczleweli commented
Messages updated, `*`es added

2022-06-09 20:03 UTC, johannbg commented
Not quite there yet... 
Squash  `fix(cli): default to correct firmware search paths` and `fix(cli): default to correct firmware search paths in dracut-install` together and change the commit message to 
`fix(dracut): default to correct firmware search paths`
also change the commit message from
`feat(rt): support ZSTD-compressed firmware with .zst suffix `
to
`feat(dracut-install): support ZSTD-compressed firmware with .zst suffix `

2022-06-09 20:32 UTC, johannbg commented
As I mentioned previously the docs need updating, just see previous commit messages touching these files.

2022-06-09 21:22 UTC, johannbg requested changes
Commit msg needs sqashing and rewording as previously mention in a comment.

2022-06-09 23:05 UTC, nabijaczleweli commented
squashed, reworded

2022-06-09 23:46 UTC, johannbg approved these changes

2022-06-09 23:46 UTC, merged

2022-06-09 23:47 UTC, johannbg commented
Thanks for your contribution sorry for the commit nitpicks and the time it took to review and merge this.