fix(dracut-initramfs-restore.sh): fix initramfs path detection
dracutdevs/dracut pull request #1983
Opened 2022-09-19 18:19 UTC by ryncsn

The path detection is not working on latest Fedora and some other distros, and fails to extract the initramfs. It seems the if statement is broken by a previous commit, so let's fix it.

Fixes: 3d8e1ad ('fix(dracut-initramfs-restore.sh): add missing default paths')
Signed-off-by: Kairui Song <kasong@tencent.com>

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes commit 3d8e1ad

2022-09-20 12:29 UTC, aafeijoo-suse requested changes
Hmm.. I think this condition is wrong, with `[[ A ]] || [[ B ]] && [[ C ]] || [[ D ]]` if only D is true the condition is met, whereas we should use here `[[ A || B ]] && [[ C || D ]]`. See a similar check (there is no need to check if MACHINE_ID is empty here):

https://github.com/dracutdevs/dracut/blob/4012314f204806a67d038f378f525646814d12ea/dracut.sh#L1128-L1139

2022-09-21 05:56 UTC, ryncsn commented
Ah, yes, you are right, the conditions are still wrong, I've fixed it again, now it should be OK.

2022-09-21 06:44 UTC, aafeijoo-suse approved these changes
The failure of TEST-10 should be unrelated.

2022-09-26 09:12 UTC, johannbg approved these changes
LGTM

2022-09-26 09:12 UTC, merged