fix(dracut-functions.sh): Suppress the findmnt error message when /etc/fstab not exist
dracutdevs/dracut pull request #2031
Opened 2022-11-03 09:57 UTC by liutgnu

When the rootfs of a virtual machine is virtiofs shared folder, the /etc/fstab file may not exist. As a result, the "findmnt --fstab" will complain "findmnt: can't read (null): No such file or directory" when trying to rebuild kdump initramfs within the vm.

This patch checks if /etc/fstab exist before calling "findmnt --fstab" to suppress the error message.

Before:
$ kdumpctl rebuild
kdump: Rebuilding /boot/initramfs-5.14.0-182.el9.x86_64kdump.img
findmnt: can't read (null): No such file or directory
findmnt: can't read (null): No such file or directory
findmnt: can't read (null): No such file or directory

After:
$ kdumpctl rebuild
kdump: Rebuilding /boot/initramfs-5.14.0-182.el9.x86_64kdump.img

Signed-off-by: Tao Liu <ltao@redhat.com>

## Changes

## Checklist
- [Y] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2022-11-03 11:37 UTC, aafeijoo-suse requested changes
You need shorten your commit message, max is 80 chars.

```
 Error: commit_message:1:81: error: commit message's subject exceeds line length of 80 by 4 characters
fix(dracut-functions.sh): suppress the findmnt error message if /etc/fstab not exist
```

Apart from that, could you prepend `$dracutsysrootdir` to `/etc/fstab` (like [dracut.sh#L1612](https://github.com/dracutdevs/dracut/blob/master/dracut.sh#L1612)) and also protect `find_mp_fsopts` and `find_dev_fsopts` in `dracut-functions.sh`? Thanks.

2022-11-04 02:09 UTC, liutgnu commented
Thanks for the comments! I have updated the code and commit message as your suggestions. @aafeijoo-suse

2022-11-04 02:44 UTC, LaszloGombos approved these changes
LGTM

2022-11-04 07:09 UTC, aafeijoo-suse approved these changes

2022-11-04 07:09 UTC, merged