ci: add test 62 to the integration test suite to test skipcpio
dracutdevs/dracut pull request #2056
Opened 2022-11-12 03:12 UTC by LaszloGombos

2022-11-18 10:26 UTC, johannbg requested changes
Can you add a bit more description about the test themselves (  50,51,62 ) which test those are and what they are testing for to the commit msg

2022-11-21 00:15 UTC, LaszloGombos commented
This is what I have in the commit message:

> Test 50,51 tests root filesystem on NFS with multiple nics.
> Test 62 tests skipcpio.

I picked these tests, as these tests are the tests currently passing without additional changes.

2022-11-21 15:43 UTC, johannbg approved these changes
@LaszloGombos it was just a minor commit nitpick being descriptive enough in our commits msg.

2022-11-22 07:33 UTC, aafeijoo-suse approved these changes

2022-11-22 07:34 UTC, merged