fix(network-manager): on machines with systemd, start the online hook…
dracutdevs/dracut pull request #2173
Opened 2023-01-19 14:39 UTC by lnykryn

…s from nm-dispatcher

So there are three steps we need to do when a NIC appears: 1) We want udev to do its stuff
2) We want NetworkManager to setup the interface
3) We want to run the online hooks

On machines without systemd this works just fine. nm-run is called after udev settles and it starts NM in the oneshoot mode and call the hooks. Everything is done nicely synchronously.

On machines with systemd, NM is started as a daemon earlier and listens to udev events. When it gets the event that device appeared it starts the configuration.

But we only run the hooks once after NM told us that it finished the setting up everything. But if an additional device appears later, we will not start the related hooks again.

So let's use NM's dispatcher to start the hooks.

This pull request changes...

## Changes

## Checklist
- [X ] I have tested it locally
- [N/A ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

2023-01-19 14:40 UTC, lnykryn commented
/cc @lkundrak @bengal @thom311 @pvalena

2023-01-19 14:45 UTC, lnykryn commented
There are two potential problems with this approach.

* Environment might not be set correctly in the online hooks.
* nm.done was previously created after NM finished and the hooks finished; now it just waits for NM

I don't see the second point as not a problem, but I may be wrong.

Anyway, I just wanted to post this PoC to get feedback.

2023-01-25 08:29 UTC, bengal commented
There are some integration tests failures that must be investigated; apart from that the approach looks good to me. 

> nm.done was previously created after NM finished and the hooks finished; now it just waits for NM

I initially suggested it, but at a second thought I'm not sure it's actually a problem. Online and netroot hooks probably can be called after the initqueue is started.

2023-01-31 09:23 UTC, aafeijoo-suse commented
> There are some integration tests failures that must be investigated; apart from that the approach looks good to me.

Tests fedora/network-manager/20 and 40 were already intermittently failing before this change.

2023-02-07 12:51 UTC, lnykryn commented
In the latest version, I got rid of nm.done completely on machines with systemd.
It was pointless, since we always created it in nm-wait-online-initrd.service which is run before initqueue.

2023-02-09 12:04 UTC, lnykryn commented
So the failed tests were not a false-positive. There were two bugs in the code. First, we need to source the dracut-status before we start the online hooks, and I had to move the start of the dispatcher to earlier because there was some weird race when using nbd.

2023-02-13 11:33 UTC, johannbg approved these changes
LGTM

2023-02-13 11:44 UTC, johannbg commented
@lnykryn just a heads up at some point Fedora/RHEL will have to carry any /etc/sysconfig/$foo downstream since it's Fedora/RHEL specific. Back in the day I was actually planning on removing it ( via feature process in Fedora ) since it should not be needed anymore in atleast Fedora but you know bureaucracy + politics...

2023-02-14 07:53 UTC, dtardon commented
> > @lnykryn just a heads up at some point Fedora/RHEL will have to carry any /etc/sysconfig/$foo downstream since it's Fedora/RHEL specific. Back in the day I was actually planning on removing it ( via feature process in Fedora ) since it should not be needed anymore in atleast Fedora but you know bureaucracy + politics...
> 
> In context of network, it should not be an issue. In fedora, we are slowly migrating to native NM configs instead of ifcfg files.

Btw, one of the blockers for this is dracut. Modules `45ifcfg` and `80cms` both create ifcfg files.

2023-02-14 16:16 UTC, aafeijoo-suse reviewed
Sorry, you have to merge the changes added in #2134.
Other than that, everything looks good and works fine, thanks.

2023-02-14 20:20 UTC, johannbg commented
> Btw, one of the blockers for this is dracut. Modules `45ifcfg` and `80cms` both create ifcfg files.

You probably mean rhel not dracut since it's not hard justifying dropping these modules here upstream even as is ( without suitable replacement ).

2023-02-15 08:04 UTC, aafeijoo-suse requested changes

2023-02-15 08:04 UTC, aafeijoo-suse commented on modules.d/35network-manager/nm-run.sh
> +if [ -e /tmp/nm.done ]; then
#2134 removed:

```bash
if [ -e /tmp/nm.done ]; then
    return
fi
```
from `nm-run.sh`

2023-02-15 13:20 UTC, bengal commented
If the command line contains a hostname (for example `ip=192.168.50.201::192.168.50.1:24:myhostname:eth0:none`), the generator writes the hostname to `/run/NetworkManager/initrd/hostname` and expects `nm-run.sh` to set it in the system. Now `nm-run.sh` no longer runs, and that hostname is not set; we need to find another way to set it, perhaps the first time the dispatcher runs, or directly from the generator.

2023-03-20 09:29 UTC, lnykryn commented
Sorry, I still plan to work on this.

2023-06-05 16:29 UTC, bengal commented
I think there are 2 issues still open:

 - the current version of the PR doesn't set the hostname for command line e.g. `ip=192.168.50.201::192.168.50.1:24:myhostname:eth0:none`. That can be solved by something like:
```diff
--- a/modules.d/35network-manager/nm-wait-online-initrd.service
+++ b/modules.d/35network-manager/nm-wait-online-initrd.service
@@ -6,11 +6,12 @@ Before=network-online.target
 Before=dracut-initqueue.service
 ConditionPathExists=/run/NetworkManager/initrd/neednet

 [Service]
 Type=oneshot
 ExecStart=/usr/bin/nm-online -s -q -t 3600
+ExecStartPost=-/bin/sh -c '[ -s /run/NetworkManager/initrd/hostname ] && cat /run/NetworkManager/initrd/hostname > /proc/sys/kernel/hostname'
 RemainAfterExit=yes

 [Install]
 WantedBy=initrd.target
 WantedBy=network-online.target
```

  Or maybe the generator should directly set the hostname in kernel instead of writing `/run/NetworkManager/initrd/hostname".


 - there is a race condition. The "up" dispatcher script isn't guaranteed to finish before the "network-online" event. So, it can happen that the initqueue starts and there is nothing to do because the dispatcher script didn't run yet. We need to add a synchronization mechanism; for example, NetworkManager should expose a "busy" flag that is set to 1 when scripts are running. nm-online should gain a new option to wait for the flag to settle, and `nm-wait-online-initrd.service` should use it in addition to `-s`.

2025-01-31 22:56 UTC, closed without merging