Always ensure /dev/{u,random} are in initramfs
dracutdevs/dracut pull request #2331
Opened 2023-05-09 22:09 UTC by cgwalters

In some scenarios, such as running `dracut` inside a podman/docker container, we may not have the capabilities necessary to create devices.

But we don't need the ability to make devices; instead, just carry a static copy of a small cpio archive with that content pre-created, and ensure it's the first thing in the generated initramfs image.

2023-05-09 22:10 UTC, cgwalters commented
(draft since this could use a bit more testing)

2023-05-10 10:42 UTC, cgwalters commented
The originating bug here is https://issues.redhat.com/browse/OCPBUGS-13207
But we shipped prior workarounds like https://github.com/coreos/rpm-ostree/pull/4058 in our wrapper for dracut.

The rationale for this is basically "server side" initramfs image builds in derived images.

2023-05-15 13:41 UTC, cgwalters commented
Yes.  For more information, see https://fedoraproject.org/wiki/Changes/OstreeNativeContainer and https://coreos.github.io/rpm-ostree/container/ - we use containers as a build tool to generate bootable host systems.  (As of recently there's also https://github.com/containers/bootc which streamlines this)

2023-05-30 13:37 UTC, cgwalters commented
> Perhaps to move this forward try to keep dracut-random.cpio.gz out of upstream and make only the necessary changes that would allow you to carry dracut-random.cpio.gz for your own needs. Would you see this as a good compromise ?

It'd help for sure, but I wouldn't call it a good compromise.  What *is* the compromise here - i.e. what do you see as bad?  Just having additional code?  The opacity of the pre-generated file (that's definitely fixable)?  Something else?

2023-07-15 13:46 UTC, cgwalters commented
This keeps coming up (e.g. https://github.com/coreos/rpm-ostree/issues/4499 ), and if we don't agree to merge this, what I'll probably end up doing is adding a wrapper around `dracut` that does it anyways.  We actually already have infrastructure for this.  It's just much less sustainable than fixing the initramfs to just have the devices by default.

2023-07-18 19:23 UTC, cgwalters commented
We could try making the cpio file at build time, but that's going to have a potentially larger blast radius - it's quite likely some build systems may actually be using container runtimes with similar device cgroup restrictions.

Another possibility is to try to land a patch in upstream `cpio` to allow it to synthesize these devices directly.

Yet another possibility is to generate a cpio blob in `dracut-install` in C code.

2023-07-24 17:50 UTC, pvalena commented
Hello,

yes, I did a brief investigation into this PR & the cpio archive is the main obstackle in bringing this even to RHEL-9 as well. 

Unfortunately, I didn't have spare cycles yet to look into what's the archive content and whether it can be recreated at dracut runtime (apart from copied from the system).

2023-07-31 12:42 UTC, ddiss commented
> Is this "cpio blob" portable across architectures (x86, x86_64, arm, arm64, etc) or they they need to be generated separate for each architecture ?

If the archive blob is just the ` /dev/{u,}random` nodes, then it shouldn't be arch specific.

I agree that it'd be nice to avoid carrying the blob in dracut. There are a couple of other options which could be considered here:
If the use-case assumes full control over the kernel, then the payload could easily be nested in the kernel via `CONFIG_INITRAMFS_SOURCE`, or a minor change to `default_cpio_list`:
```
--- a/usr/default_cpio_list
+++ b/usr/default_cpio_list
@@ -4,3 +4,5 @@
 dir /dev 0755 0 0
 nod /dev/console 0600 0 0 c 5 1
 dir /root 0700 0 0
+nod /dev/random 0666 0 0 c 1 8
+nod /dev/urandom 0666 0 0 c 1 9
```

Still, the underlying problem here is the source-directory-tree-defines-archive-contents interface for GNU cpio (which is copied for dracut-cpio, which breaks unprivileged archive creation. My plan is to address this with https://github.com/dracutdevs/dracut/issues/1662 , which will add a Linux `gen_init_cpio` like interface to dracut-cpio.

2023-07-31 13:55 UTC, ddiss requested changes

2023-08-03 10:30 UTC, ddiss commented on Makefile
> +	install -m 0644 -Dt $(DESTDIR)$(pkglibdir) dracut-random.cpio.gz
One thing I forgot to mention: GNU cpio unnecessarily zero-pads archives out to the next "block-size" (default=512) alignment, while the newc / SVR4 spec only requires 4-byte alignment, so any bundled archive with GNU cpio padding could be trimmed down.
In matching GNU cpio quirks, dracut-cpio does the same:
https://github.com/dracutdevs/dracut/blob/master/src/dracut-cpio/src/main.rs#L644

2023-10-12 12:09 UTC, cgwalters commented
Closing since we're in agreement this exact patch isn't the way to go

2023-10-12 12:09 UTC, closed without merging

2023-11-02 13:53 UTC, ericcurtin commented
> Is this "cpio blob" portable across architectures (x86, x86_64, arm, arm64, etc) or they they need to be generated separate for each architecture ?

Note, it's important that the solution is also portable across compressors/decompressors (gzip, lz4, zstd, etc.) Encountered an issue where part of the initramfs was lz4 and another part gzip and the kernel decompressor got confused and panicked on boot.