fix(test): running tests no longer requires to be root
dracutdevs/dracut pull request #2429
Opened 2023-07-14 02:10 UTC by Henrik66

After https://github.com/dracutdevs/dracut/commit/fd9cd02cb21f25d32fec4cd9889457ea6361f45e, tests no longer requires to be root. Being able to run VMs to run tests is required, but that should not imply root user.

Fixes https://github.com/dracutdevs/dracut/issues/1147 and https://bugs.gentoo.org/298014

2023-07-14 11:35 UTC, LaszloGombos approved these changes
Thanks.

I will close https://github.com/dracutdevs/dracut/pull/2217 in favor of this PR.

2023-07-17 13:20 UTC, aafeijoo-suse reviewed
FWIW, this line would also have to be removed:

https://github.com/dracutdevs/dracut/blob/6af3fcfd7f699ec4bb3f1e9ac71b7a9ebb9804b3/test/Makefile#L4

2023-07-17 20:09 UTC, Henrik66 commented
> FWIW, this line would also have to be removed:
> 
> https://github.com/dracutdevs/dracut/blob/6af3fcfd7f699ec4bb3f1e9ac71b7a9ebb9804b3/test/Makefile#L4

Thanks @aafeijoo-suse for the review.
Unfortunately, I do not understand what else needs to be removed as the line 4 of test/Makefile is already removed in this PR - see https://github.com/dracutdevs/dracut/pull/2429/files#diff-740cb5a1689091cb894445e46683c255e39689ccba1c6c63d8a8841c8df8817dL4 . Can you help me understand please ! Thanks !

2023-07-18 06:05 UTC, aafeijoo-suse commented
> > FWIW, this line would also have to be removed:
> > https://github.com/dracutdevs/dracut/blob/6af3fcfd7f699ec4bb3f1e9ac71b7a9ebb9804b3/test/Makefile#L4
> 
> Thanks @aafeijoo-suse for the review. Unfortunately, I do not understand what else needs to be removed as the line 4 of test/Makefile is already removed in this PR - see https://github.com/dracutdevs/dracut/pull/2429/files#diff-740cb5a1689091cb894445e46683c255e39689ccba1c6c63d8a8841c8df8817dL4 . Can you help me understand please ! Thanks !

Sorry, I missed that change somehow... it's all good

2023-08-15 23:08 UTC, bdrung commented
+1 from my side. I tested the patch from this PR plus https://github.com/dracutdevs/dracut/pull/2484 successfully for the tests 01 02 03 04 on Debian and Ubuntu.

One caveat: The kernel on Ubuntu is only readable by root. So either make it readable or run as root. See https://launchpad.net/bugs/759725

2023-08-19 12:44 UTC, bdrung requested changes
Please remove `sudo` from the Docker files in `test/container/`.

2023-08-19 13:29 UTC, bdrung approved these changes

2023-10-31 14:14 UTC, LaszloGombos approved these changes

2024-04-06 22:40 UTC, closed without merging