fix(systemd-pcrphase): rename systemd-pcrphase binary to systemd-pcrextend
dracutdevs/dracut pull request #2526
Opened 2023-09-26 06:15 UTC by aafeijoo-suse

The `systemd-pcrphase` binary has been renamed to `systemd-pcrextend` since https://github.com/systemd/systemd/commit/32295fa0

This patch will be necessary for systemd-v255.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

2023-12-10 23:42 UTC, LaszloGombos approved these changes

2023-12-11 08:28 UTC, lnykryn commented
Wouldn't this break compatibility with older systemd?

2023-12-12 00:12 UTC, ferringb commented
> Wouldn't this break compatibility with older systemd?

yep.

2023-12-12 07:16 UTC, aafeijoo-suse commented
> Wouldn't this break compatibility with older systemd?

Yes, `systemd-pcrphase` was introduced in systemd-v252. I thought that our current upstream policy was to support only the latest version of other upstream dependencies, otherwise this is unmanageable.

2023-12-13 01:39 UTC, LaszloGombos reviewed
CI is still on systemd-v252

2023-12-13 01:42 UTC, LaszloGombos requested changes
CI is still on systemd-v252

2025-01-31 23:56 UTC, closed without merging