Retrieve service, rpc and protcol entries via getent
dracutdevs/dracut pull request #778
Opened 2020-03-27 14:02 UTC by danimo

Sometimes, systems have more elaborate backends in nsswitch.conf,
the complexity of which we do not want in the initrd. SUSE systems
with atomic for instance, where those files may also reside in /usr/etc.

With this change, the unavaiable nsswitch.conf backends will be silently
ignored, and we still end up with all the information we need.

Reference: boo#1165366

2020-03-27 14:03 UTC, danimo commented
This also has the neat side effect that we no longer ignore NIS or LDAP-based entries for those files.

2020-03-27 14:04 UTC, danimo commented
Downstream Bug-Report: https://bugzilla.suse.com/show_bug.cgi?id=1165366

2020-06-19 13:12 UTC, haraldh commented
> Downstream Bug-Report: https://bugzilla.opensuse.org/show_bug.cgi?id=1165366

https://bugzilla.opensuse.org/show_bug.cgi?id=1165366#c18

2020-06-19 13:13 UTC, haraldh commented
> This also has the neat side effect that we no longer ignore NIS or LDAP-based entries for those files.

Aren't these dynamic? I think this be dependent on `$hostonly`

2020-08-04 23:38 UTC, danimo commented
Done. Also removed the changes for the tests, as they are not hostonly.

2020-08-26 13:39 UTC, haraldh requested changes

2020-08-26 13:39 UTC, haraldh commented on modules.d/95cifs/module-setup.sh
> +        getent protocols > ${initdir}/etc/services
```suggestion
        getent protocols > ${initdir}/etc/protocols
```

2020-08-26 13:39 UTC, haraldh commented on modules.d/95cifs/module-setup.sh
> +        inst_multiple /etc/services /etc/services
what happened to `/etc/protocols` ??

2020-11-14 18:28 UTC, merged