Adding btrfs udev rules might fix issue 947
dracutdevs/dracut pull request #948
Opened 2020-10-16 19:37 UTC by johannbg

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2020-11-14 18:35 UTC, danimo requested changes
See comment.

2020-11-14 18:35 UTC, danimo commented on modules.d/95udev-rules/module-setup.sh
> +	64-btrfs-dm.rules \
Please fix indentation.

2020-11-18 13:20 UTC, haraldh commented
looks good, although I would add them in `modules.d/90btrfs`

2020-11-18 22:12 UTC, johannbg commented
@haraldh yeah I came to the same conclusion along with remove all this legacy cruff that is in that module. From my pov dracut should do a release then after that we need to seriously re-facture-it/rework it and remove all that legacy cruff like that old ( btrfs ) rules file etc. On top of that I took a wee bit closer look at that 64-btrfs-dm.rules I included and is being shipped with btrfs-progs in fedora and seems to be broken so that needs fixing in the *right* place as well so arguably we should not be including it. @haraldh @danimo thanx for reviewing this.

2020-11-25 17:39 UTC, danimo commented
@haraldh fine with merging as-is?

2020-11-25 18:05 UTC, haraldh commented
> @haraldh fine with merging as-is?

@danimo yes

2020-11-25 19:56 UTC, johannbg commented
@danimo @haraldh Note that 64-btrfs-dm.rules ( which come from btrfs-progs ) and I included are outdated and probably break with systemd 247+ so by adding it we might be signing ourselves up for more issues.

2020-12-26 09:08 UTC, johannbg commented
.

2021-01-16 22:37 UTC, cmurf commented
I don't see how /usr/lib/udev/rules.d/64-btrfs-dm.rules would fix #947. What's missing from the initrd in that bug is /usr/lib/udev/rules.d/64-btrfs.rules to make sure systemd waits for all btrfs devices to be ready before trying to mount. 

/usr/lib/udev/rules.d/64-btrfs.rules is part of systemd

/usr/lib/udev/rules.d/64-btrfs-dm.rules is part of btrfs-progs, if that's somehow stale or out of date, it needs an issue filed with [btrfsprogs](https://github.com/kdave/btrfs-progs/issues)

2021-01-17 07:23 UTC, johannbg commented
Let's start by getting the udev rules into the reporters initramfs before claiming that it's not the problem and I'm very well aware of where I could file reports against btrfs-prog and those rules are broken ( as well as bunch of other udev rules ) but thanks for the info. We will look at this properly when we have the time...

2021-01-17 08:53 UTC, cmurf commented
The [problem is resolved](https://ask.fedoraproject.org/t/btrfs-volume-mount-fails-at-boot-but-works-once-system-is-up/9593/23?u=chrismurphy) when `dracut -f --add btrfs` is used, which results in usr/lib/udev/rules.d/64-btrfs.rules being included in the initramfs. Whereas /usr/lib/udev/rules.d/64-btrfs-dm.rules is absent. In the original report, as well as my testing, dm isn't being used for anything.

2021-01-17 08:55 UTC, closed without merging